apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment2
  namespace: app2
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: the-container
        image: busybox:1.32