apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  destination:
  source:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true