apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment1
  namespace: app1
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: the-container
        image: monopole/hello:2
