namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
bases:
- ../../../base/app1
#namespace: production-argo-test
patchesStrategicMerge:
- deployment.yaml
