namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
bases:
- ../../../base/app1
patchesStrategicMerge:
- deployment.yaml
- app.yaml

