apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment1
  namespace: app1
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: the-container
        image: monopole/hello:2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment2
  namespace: app2
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: the-container
        image: monopole/hello:2