kind: Service
apiVersion: v1
metadata:
  name: the-service1
  namespace: app1
spec:
  selector:
    deployment: hello1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
