namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
resources:
- namespace.yaml
bases:
- ../../base
namespace: green-production
patchesStrategicMerge:
- deployment.yaml
