apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stagingworking
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://10.131.228.112:6443'
  source:
    repoURL: 'https://github.com/alexcpn/argocd-demo'
    path: examples/overlays/staging_working/
    targetRevision: v1.3
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  kustomize:
      version: v3.8.2