# Default Values for 

spec:
  production:
    destination:
      server: 'https://10.131.228.112:6443'
  staging:
    destination:
      server: 'https://kubernetes.default.svc'
      
  destination:
    cluster1tag: v.200.2
    cluster2tag: v.300.1