# Default Values for 

spec:
  production:
    destination:
      server: 'https://10.131.228.112:6443'
  staging1:
    destination:
      server: 'https://kubernetes.default.svc'
  staging2:
    destination:
      server: 'https://10.131.228.112:6443'
      
  destination:
    production: main
    staging1: v.300.1
    staging2: v.200.2