apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/alexcpn/argocd-demo'
    path: examples/overlays/production/app2
    targetRevision: HEAD
    directory:
      recurse: false
