namePrefix: staging-
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../../../base/app1
namespace: staging-green
patchesStrategicMerge:
- map.yaml
